AUTHN_HEADER=X-Auth-Token
AUTHN_TOKEN=mysmarthireapitoken123mysecretkey12345678901234567890ab
ENABLE_BATCHED_SUBMISSIONS=true
ENABLE_WAIT_RESULT=true
MAX_CPU_TIME_LIMIT=5
MAX_MEMORY_LIMIT=512000
MAX_QUEUE_SIZE=200
POSTGRES_DB=judge0_mljw
POSTGRES_HOST=dpg-d6uecc7fte5s738bk0h0-a
POSTGRES_PASSWORD=Zyk442opLAygcR6SlC0PdINvB49TTumF
POSTGRES_PORT=5432
POSTGRES_USER=judge0
REDIS_URL=redis://red-d6uefd75gffc739lsukg:6379
SECRET_KEY=mysecretkey12345678901234567890ab
WEB_CONCURRENCY=2
